#!/bin/bash

echo "🔧 修复应用检测问题"
echo "==================="

PROJECT_DIR="/Users/weifu/Desktop/AITouchGrass"
cd "$PROJECT_DIR"

echo "📊 问题分析："
echo "============="
echo "- 你定义了160+个应用，但iOS限制每个应用最多只能检测50个URL schemes"
echo "- 这就是为什么只检测到13个应用的原因"
echo "- Apple在iOS 9后引入了LSApplicationQueriesSchemes限制"
echo "- 必须在Info.plist中预先声明要检测的URL schemes"

echo ""
echo "✅ 已完成的修复："
echo "================"
echo "1. 重新设计RealAppDetectionService，只包含50个最重要的应用"
echo "2. 优先选择中国最受欢迎的应用（微信、QQ、支付宝、淘宝等）"
echo "3. 添加国际流行应用（Instagram、WhatsApp、YouTube等）"
echo "4. 修复URL scheme格式问题"
echo "5. 改进调试输出"

echo ""
echo "🎯 优先级策略："
echo "==============="
echo "**高优先级（前15个）：**"
echo "- 微信、QQ、支付宝、淘宝、抖音"
echo "- 微博、小红书、B站、快手、网易云音乐"
echo "- 高德地图、美团、饿了么、滴滴出行、京东"

echo ""
echo "**中优先级（16-35个）：**"
echo "- QQ音乐、知乎、今日头条、百度、百度地图"
echo "- 拼多多、天猫、爱奇艺、腾讯视频、优酷"
echo "- Instagram、WhatsApp、YouTube、TikTok等"

echo ""
echo "**基础优先级（36-47个）：**"
echo "- 游戏应用、其他社交应用、系统应用等"

echo ""
echo "⚠️ 需要手动配置LSApplicationQueriesSchemes："
echo "============================================="

echo "1. 在Xcode中打开项目"
echo "2. 选择AITouchGrass target"
echo "3. 点击Info标签页"
echo "4. 添加Key: LSApplicationQueriesSchemes (Array类型)"
echo "5. 添加以下50个URL schemes (不包含://后缀)："

echo ""
echo "weixin"
echo "mqq"
echo "alipay"
echo "taobao"
echo "snssdk1128"
echo "sinaweibo"
echo "xhsdiscover"
echo "bilibili"
echo "kwai"
echo "orpheus"
echo "iosamap"
echo "imeituan"
echo "eleme"
echo "diditaxi"
echo "openapp.jdmobile"
echo "qqmusic"
echo "zhihu"
echo "snssdk141"
echo "baiduboxapp"
echo "baidumap"
echo "pinduoduo"
echo "tmall"
echo "qiyi-iphone"
echo "tenvideo"
echo "youku"
echo "instagram"
echo "whatsapp"
echo "youtube"
echo "musically"
echo "fb"
echo "twitter"
echo "tg"
echo "nflx"
echo "spotify"
echo "googlechrome"
echo "smoba"
echo "pubgmobile"
echo "genshinimpact"
echo "discord"
echo "snapchat"
echo "linkedin"
echo "uber"
echo "prefs"
echo "mailto"
echo "tel"
echo "sms"
echo "http"
echo "maps"
echo "itms-apps"

echo ""
echo "🚀 配置完成后的预期结果："
echo "========================="
echo "- 应该能检测到20-30个应用（取决于你安装了哪些）"
echo "- 所有主流中国应用都能被检测"
echo "- 常用国际应用也能被检测"
echo "- 系统应用能正常显示"

echo ""
echo "📋 测试步骤："
echo "============"
echo "1. 按上述步骤添加LSApplicationQueriesSchemes"
echo "2. Clean Build Folder"
echo "3. 重新构建应用"
echo "4. 在真机上测试应用选择功能"
echo "5. 查看控制台输出的调试信息"

echo ""
echo "🔍 故障排除："
echo "============"
echo "如果仍然检测不到足够的应用："
echo "- 确保LSApplicationQueriesSchemes配置正确"
echo "- 检查应用确实安装在设备上"
echo "- 查看Xcode控制台的调试输出"
echo "- 确保在真机而不是模拟器上测试"

echo ""
echo "💡 技术说明："
echo "============"
echo "- iOS 9后，canOpenURL需要预先在Info.plist中声明"
echo "- 每个应用最多50个schemes的硬限制"
echo "- 这是Apple的隐私保护措施，无法绕过"
echo "- 我们选择了最常用的50个应用以获得最佳覆盖率"

echo ""
echo "✅ 修复完成！请按照上述步骤配置LSApplicationQueriesSchemes。"